-- Expanded workflow_logs v2 - backend only
create table if not exists workflow_logs (
  id bigint generated by default as identity primary key,
  workflow_run_id uuid references workflow_runs(id) on delete cascade not null,
  step text not null,
  substep text not null,
  sequence_number int not null,
  log_level text default 'info' check (log_level in ('info', 'warn', 'error')),
  status text default 'running' check (status in ('running', 'done', 'error')),
  metadata jsonb default '{}',
  started_at timestamptz default now(),
  completed_at timestamptz,
  error_message text,
  trace_id uuid default gen_random_uuid(),
  created_at timestamptz default now()
);

create index idx_workflow_logs_run_step on workflow_logs(workflow_run_id, step, sequence_number);
create index idx_workflow_logs_level_status on workflow_logs(log_level, status);
create index idx_workflow_logs_created on workflow_logs(created_at desc);

alter publication supabase_realtime add table workflow_logs;

-- Optional view (backend only)
create view active_workflow_steps as
select workflow_run_id, step, array_agg(substep order by sequence_number) as substeps
from workflow_logs where status = 'running' group by workflow_run_id, step;
