-- ── workflow_logs: sub-step streaming for live progress bullets ──────────────
-- Inserted by edge functions (service role) as each sub-step starts/finishes.
-- The frontend subscribes via Supabase Realtime (postgres_changes INSERT)
-- filtered to the current workflow_run_id.

CREATE TABLE IF NOT EXISTS public.workflow_logs (
  id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_run_id uuid        REFERENCES public.workflow_runs(id) ON DELETE CASCADE,
  step            text        NOT NULL,            -- TRANSMIT / INTENT / ANALYZE / etc.
  substep         text        NOT NULL,            -- human-readable sub-step label
  status          text        NOT NULL DEFAULT 'running', -- running / done / error
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS workflow_logs_run_id_idx  ON public.workflow_logs (workflow_run_id);
CREATE INDEX IF NOT EXISTS workflow_logs_created_idx ON public.workflow_logs (created_at DESC);

-- Row-Level Security
ALTER TABLE public.workflow_logs ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read logs for workflow runs they own.
-- Service role (used by edge functions) bypasses RLS.
CREATE POLICY "Users can view logs for own workflow runs"
  ON public.workflow_logs
  FOR SELECT
  TO authenticated
  USING (
    workflow_run_id IN (
      SELECT id FROM public.workflow_runs WHERE user_id = auth.uid()
    )
  );

-- Enable Realtime so frontend postgres_changes subscription works
ALTER PUBLICATION supabase_realtime ADD TABLE public.workflow_logs;
